--------------------------------------------------------
--  File created - Thursday-June-01-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PELANGGAN
--------------------------------------------------------

  CREATE TABLE "GLOBAL"."PELANGGAN" 
   (	"NO_PELANGGAN" NUMBER, 
	"NAMA_PELANGGAN" VARCHAR2(50 BYTE), 
	"ALAMAT_PELANGGAN" VARCHAR2(200 BYTE), 
	"KOTA_PELANGGAN" VARCHAR2(30 BYTE), 
	"PROPINSI_PELANGGAN" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GLO" ;
REM INSERTING into GLOBAL.PELANGGAN
SET DEFINE OFF;
Insert into GLOBAL.PELANGGAN (NO_PELANGGAN,NAMA_PELANGGAN,ALAMAT_PELANGGAN,KOTA_PELANGGAN,PROPINSI_PELANGGAN) values (1000,'Beckham','Sukolilo','Surabaya','Jawa Timur');
Insert into GLOBAL.PELANGGAN (NO_PELANGGAN,NAMA_PELANGGAN,ALAMAT_PELANGGAN,KOTA_PELANGGAN,PROPINSI_PELANGGAN) values (2000,'Ronaldo','Ngagel','Surabaya','Jawa Timur');
Insert into GLOBAL.PELANGGAN (NO_PELANGGAN,NAMA_PELANGGAN,ALAMAT_PELANGGAN,KOTA_PELANGGAN,PROPINSI_PELANGGAN) values (3000,'Ibrahimovic','Batu','Malang','Jawa Timur');
Insert into GLOBAL.PELANGGAN (NO_PELANGGAN,NAMA_PELANGGAN,ALAMAT_PELANGGAN,KOTA_PELANGGAN,PROPINSI_PELANGGAN) values (4000,'Messi','Kuta','Denpasar','Bali');
Insert into GLOBAL.PELANGGAN (NO_PELANGGAN,NAMA_PELANGGAN,ALAMAT_PELANGGAN,KOTA_PELANGGAN,PROPINSI_PELANGGAN) values (5000,'Militio','Kebayoran Baru','Jakarta','DKI');
Insert into GLOBAL.PELANGGAN (NO_PELANGGAN,NAMA_PELANGGAN,ALAMAT_PELANGGAN,KOTA_PELANGGAN,PROPINSI_PELANGGAN) values (6000,'Kaka','Menteng','Jakarta','DKI');
Insert into GLOBAL.PELANGGAN (NO_PELANGGAN,NAMA_PELANGGAN,ALAMAT_PELANGGAN,KOTA_PELANGGAN,PROPINSI_PELANGGAN) values (7000,'Puyol','Serpong','Tangerang','Jawa Barat');
Insert into GLOBAL.PELANGGAN (NO_PELANGGAN,NAMA_PELANGGAN,ALAMAT_PELANGGAN,KOTA_PELANGGAN,PROPINSI_PELANGGAN) values (8000,'Henry','Bandung','Bandung','Jawa Barat');
Insert into GLOBAL.PELANGGAN (NO_PELANGGAN,NAMA_PELANGGAN,ALAMAT_PELANGGAN,KOTA_PELANGGAN,PROPINSI_PELANGGAN) values (9000,'Ronaldinho','Legian','Denpasar','Bali');
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GLOBAL"."TABLE1_PK" ON "GLOBAL"."PELANGGAN" ("NO_PELANGGAN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GLO" ;
--------------------------------------------------------
--  Constraints for Table PELANGGAN
--------------------------------------------------------

  ALTER TABLE "GLOBAL"."PELANGGAN" MODIFY ("NO_PELANGGAN" NOT NULL ENABLE);
 
  ALTER TABLE "GLOBAL"."PELANGGAN" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("NO_PELANGGAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GLO"  ENABLE;
