--------------------------------------------------------
--  File created - Thursday-June-01-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUK
--------------------------------------------------------

  CREATE TABLE "GLOBAL"."PRODUK" 
   (	"NO_PRODUK" NUMBER, 
	"NAMA_PRODUK" VARCHAR2(50 BYTE), 
	"KATEGORI_PRODUK" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GLO" ;
REM INSERTING into GLOBAL.PRODUK
SET DEFINE OFF;
Insert into GLOBAL.PRODUK (NO_PRODUK,NAMA_PRODUK,KATEGORI_PRODUK) values (101,'Give','Sabun Mandi');
Insert into GLOBAL.PRODUK (NO_PRODUK,NAMA_PRODUK,KATEGORI_PRODUK) values (102,'Rinso','Sabun Cuci');
Insert into GLOBAL.PRODUK (NO_PRODUK,NAMA_PRODUK,KATEGORI_PRODUK) values (103,'Pepsodent','Pasta Gigi');
Insert into GLOBAL.PRODUK (NO_PRODUK,NAMA_PRODUK,KATEGORI_PRODUK) values (104,'Formula','Pasta Gigi');
Insert into GLOBAL.PRODUK (NO_PRODUK,NAMA_PRODUK,KATEGORI_PRODUK) values (105,'Djarum Super','Rokok');
Insert into GLOBAL.PRODUK (NO_PRODUK,NAMA_PRODUK,KATEGORI_PRODUK) values (106,'Djisamsoe','Rokok');
Insert into GLOBAL.PRODUK (NO_PRODUK,NAMA_PRODUK,KATEGORI_PRODUK) values (107,'Sun Light','Sabun Cuci');
--------------------------------------------------------
--  DDL for Index PRODUK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GLOBAL"."PRODUK_PK" ON "GLOBAL"."PRODUK" ("NO_PRODUK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GLO" ;
--------------------------------------------------------
--  Constraints for Table PRODUK
--------------------------------------------------------

  ALTER TABLE "GLOBAL"."PRODUK" ADD CONSTRAINT "PRODUK_PK" PRIMARY KEY ("NO_PRODUK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GLO"  ENABLE;
 
  ALTER TABLE "GLOBAL"."PRODUK" MODIFY ("NO_PRODUK" NOT NULL ENABLE);
